org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

minecraft_version = 26.1
minecraft_version_range=[26.1,27.1)
forge_version = 26.1.0.17-beta
forge_version_range=[26.1,27.1)
loader_version_range=[4,)

jei_version = 29.2.0.20
baubles_version = 1.0
baubles_gradle = 7848274-sources
terrablender_gradle = 7834071

mod_id = thaumcraft
mod_name = Thaumcraft
mod_license = ARR
mod_version = 0.1
mod_authors = Tanticle, NextdoorPsycho
mod_description = Adding a touch of legally distinct magic to Minecraft.